# This file contains the secrets required to connect to the SQL Server database and SSRS server.
# This file is not included in the repository, as it contains sensitive information.
# Please contact the project team for access to this file.

[mydb]
# Connection details for the SQL Server database using to Produce Python Reports/ Dashboards
dialect = "mssql"
driver = "ODBC Driver 17 for SQL Server"  # Specify the ODBC driver
username = "sa"
password = "1984Icm000"
host = "192.168.5.182"  # IP address of the SQL Server
port = "1433"  # Default SQL Server port
database = "Infeed700"
enecoms_database = "Enecoms"
instance = "MSSQLSERVER"  # Optional: Include the instance name if needed

[ssrs_config]
# Connection details for the SSRS server
ipAddress = "192.168.5.182"
port = "80"
database = "Infeed700"
database-enecoms= 'Enecoms'
ReportServerName = "Reportsmanager"
username = "DASMILL\\Reports"
password = "Reporting123"

[streamlit_server]
ip_address = "localhost"
port = "8501"