# This file contains the secrets required to connect to the SQL Server database and SSRS server.
# This file is not included in the repository, as it contains sensitive information.
# Please contact the project team for access to this file.

[sidebar]
selected_item_color = "#056003"      #Color of the selected item in the sidebar menu 
icon_color = "#022601"               # Color of the icons in the sidebar menu

[secrets_config]
secrets_name = "secrets_dgl"

[site_info]
site_name = 'LIVE - DGL'

[release]
current_release = 'Release 1.0'